import { test } from "node:test";
import assert from "node:assert/strict";
import { execFileSync } from "node:child_process";
import { mkdirSync, mkdtempSync, rmSync, symlinkSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { tmpdir } from "node:os";
import { runAudit, renderMarkdown } from "../scripts/audit.ts";
import { TOOL_VERSION } from "../scripts/transform.ts";

/** Fresh fixture repo (not a git repo — maturity checks just under-score). */
function fixture(): string {
  return mkdtempSync(join(tmpdir(), "spooner-audit-"));
}

function item(repo: string, id: string) {
  return runAudit(repo).items.find((i) => i.id === id);
}

function git(repo: string, args: string[], env?: Record<string, string>): void {
  execFileSync("git", args, { cwd: repo, stdio: "ignore", env: env ? { ...process.env, ...env } : undefined });
}

// --- acceptance 1: scale ----------------------------------------------------

test("scale: full marks = 10 (9.5 is the excellent benchmark, not a cap), maxima 4.5/2/1.5/0.5/1.5, every score is a 0.1 multiple", () => {
  const repo = fixture();
  const r = runAudit(repo);
  assert.equal(r.schemaVersion, 3);
  assert.equal(r.score.max, 10);
  assert.equal(r.score.byCategory["agent-setup"].max, 4.5);
  assert.equal(r.score.byCategory.configuration.max, 2);
  assert.equal(r.score.byCategory.integrity.max, 1.5);
  assert.equal(r.score.byCategory.freshness.max, 0.5);
  assert.equal(r.score.byCategory.structure.max, 1.5);
  for (const i of r.items) {
    assert.ok(i.score <= i.max, `${i.id}: score ${i.score} > max ${i.max}`);
    const scaled = i.score * 10;
    assert.ok(Math.abs(scaled - Math.round(scaled)) < 1e-9, `${i.id}: ${i.score} is not a 0.1 multiple`);
  }
  for (const [cat, v] of Object.entries(r.score.byCategory)) {
    assert.ok(v.score <= v.max, `${cat}: ${v.score} > max ${v.max}`);
  }
  // no ×0.95 scaling — total is the plain weighted sum (max 10)
  const raw = Object.values(r.score.byCategory).reduce((s, v) => s + v.score, 0);
  assert.equal(r.score.total, Math.round(raw * 10) / 10);
  assert.ok(r.score.total <= 10, `total ${r.score.total} exceeds max`);
  rmSync(repo, { recursive: true, force: true });
});

test("scale: totals carry no float tails — 0.1 display granularity (regression: 1.4000000000000001)", () => {
  const repo = fixture();
  writeFileSync(join(repo, "package.json"), '{"name":"x"}\n');
  writeFileSync(join(repo, "eslint.config.js"), "module.exports = {};\n");
  writeFileSync(join(repo, ".prettierrc"), "{}\n");
  writeFileSync(
    join(repo, ".pre-commit-config.yaml"),
    "repos:\n  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook\n    rev: v9.26.0\n",
  );
  const r = runAudit(repo);
  for (const [cat, v] of Object.entries(r.score.byCategory)) {
    assert.ok(Number.isInteger(v.score * 10), `${cat}: ${v.score} has a float tail`);
  }
  assert.ok(Number.isInteger(r.score.total * 10), `total ${r.score.total} has a float tail`);
  assert.equal(r.score.byCategory.configuration.score, 0.5);
  assert.equal(r.score.total, 1.2);
  rmSync(repo, { recursive: true, force: true });
});

test("freshness: activity is not scored — a dormant repo matches an active one (2026-08-07)", () => {
  const build = (commitDate: string) => {
    const repo = fixture();
    git(repo, ["init", "-q"]);
    writeFileSync(join(repo, "package.json"), '{"name":"x","scripts":{"test":"true"}}\n');
    git(repo, ["add", "."]);
    // CI runners have no global git identity — a bare commit fails there
    // ("Please tell me who you are") while local machines pass (2026-08-07).
    git(repo, ["commit", "-q", "-m", "init"], {
      GIT_AUTHOR_DATE: commitDate,
      GIT_COMMITTER_DATE: commitDate,
      GIT_AUTHOR_NAME: "test",
      GIT_AUTHOR_EMAIL: "test@example.com",
      GIT_COMMITTER_NAME: "test",
      GIT_COMMITTER_EMAIL: "test@example.com",
    });
    return repo;
  };
  const active = build("2026-08-01T00:00:00Z");
  const dormant = build("2024-01-01T00:00:00Z");
  const ra = runAudit(active);
  const rd = runAudit(dormant);
  assert.equal(rd.score.total, ra.score.total, "dormant repo must score identically to an active one");
  assert.ok(
    !rd.items.some((i) => i.id.startsWith("fresh-") && i.id !== "fresh-deps"),
    "activity checks (fresh-recent/fresh-active) must not exist",
  );
  rmSync(active, { recursive: true, force: true });
  rmSync(dormant, { recursive: true, force: true });
});

// --- acceptance 2: quality grading (generated-contract fixture) --------------

test("agents: generated-contract fixture scores top bands", () => {
  const repo = fixture();
  writeFileSync(
    join(repo, "package.json"),
    '{"name":"x","scripts":{"build":"echo b","test":"echo t","lint":"echo l"}}\n',
  );
  // 42-line contract with two traceable commands
  const contract = [
    "# x — agent contract",
    "> Generated by spooner transform Stage 3.",
    "## Overview",
    "Demo.",
    "## Commands (all real and executable)",
    "| Command | Purpose |",
    "|---|---|",
    "| `npm run build` | build |",
    "| `npm run test` | test |",
    "",
  ].concat(Array.from({ length: 32 }, (_, i) => `line ${i}`));
  writeFileSync(join(repo, "AGENTS.md"), contract.join("\n"));
  // symlink bridge
  mkdirSync(join(repo, ".git"), { recursive: true });
  writeFileSync(join(repo, ".git", "HEAD"), "ref: refs/heads/main\n");
  try {
    symlinkSync("AGENTS.md", join(repo, "CLAUDE.md"));
  } catch {
    /* symlink may fail on some platforms — bridge test is best-effort */
  }
  assert.equal(item(repo, "agents-md")?.score, 0.5);
  assert.equal(item(repo, "agents-length")?.score, 0.5);
  const bridge = item(repo, "agents-bridge");
  if (bridge) assert.ok([0.5, 0.3].includes(bridge.score), `bridge ${bridge.score}`);
  rmSync(repo, { recursive: true, force: true });
});

// --- acceptance 3: length banding -------------------------------------------

test("agents-length: 42-line contract -> 0.5 (optimal band)", () => {
  const repo = fixture();
  writeFileSync(join(repo, "AGENTS.md"), Array.from({ length: 42 }, (_, i) => `line ${i}`).join("\n"));
  assert.equal(item(repo, "agents-length")?.score, 0.5);
  rmSync(repo, { recursive: true, force: true });
});

test("agents-length: 220-line contract drops to 0.3", () => {
  const repo = fixture();
  writeFileSync(join(repo, "AGENTS.md"), Array.from({ length: 220 }, (_, i) => `line ${i}`).join("\n"));
  assert.equal(item(repo, "agents-length")?.score, 0.3);
  rmSync(repo, { recursive: true, force: true });
});

// --- acceptance 4: CI depth --------------------------------------------------

function ciFixture(workflow: string): string {
  const repo = fixture();
  mkdirSync(join(repo, ".github", "workflows"), { recursive: true });
  writeFileSync(join(repo, ".github", "workflows", "ci.yml"), workflow);
  return repo;
}

test("cfg-ci: lint-only workflow -> 0.2", () => {
  const repo = ciFixture("jobs:\n  lint:\n    runs-on: ubuntu-latest\n    steps: [{ run: npm run lint }]\n");
  assert.equal(item(repo, "cfg-ci")?.score, 0.2);
  rmSync(repo, { recursive: true, force: true });
});

test("cfg-ci: lint+test -> 0.4", () => {
  const repo = ciFixture("jobs:\n  lint:\n    runs-on: ubuntu-latest\n  test:\n    runs-on: ubuntu-latest\n");
  assert.equal(item(repo, "cfg-ci")?.score, 0.4);
  rmSync(repo, { recursive: true, force: true });
});

test("cfg-ci: lint+test+security job -> 0.5", () => {
  const repo = ciFixture(
    "jobs:\n  lint:\n    runs-on: ubuntu-latest\n  test:\n    runs-on: ubuntu-latest\n  security:\n    runs-on: ubuntu-latest\n",
  );
  assert.equal(item(repo, "cfg-ci")?.score, 0.5);
  rmSync(repo, { recursive: true, force: true });
});

test("cfg-ci: no CI files -> 0 (regression: hasCi false positive)", () => {
  const repo = fixture();
  const r = item(repo, "cfg-ci");
  assert.equal(r?.score, 0);
  assert.match(r?.evidence ?? "", /no CI config found/);
  rmSync(repo, { recursive: true, force: true });
});

test("cfg-ci: gitlab CI with lint+test counts (cross-platform honesty)", () => {
  const repo = fixture();
  writeFileSync(join(repo, ".gitlab-ci.yml"), "stages: [lint, test]\n");
  assert.equal(item(repo, "cfg-ci")?.score, 0.4);
  rmSync(repo, { recursive: true, force: true });
});

// --- acceptance 5: drift quality ---------------------------------------------

test("drift: no manifest -> 0", () => {
  const repo = fixture();
  assert.equal(item(repo, "drift")?.score, 0);
  rmSync(repo, { recursive: true, force: true });
});

test("drift: stale manifest (version != tool) -> 0.2, never full", () => {
  const repo = fixture();
  writeFileSync(join(repo, ".ai-native.yml"), `schemaVersion: 1\ntool: spooner\nversion: "0.0.1"\nstages: {}\n`);
  assert.equal(item(repo, "drift")?.score, 0.2);
  rmSync(repo, { recursive: true, force: true });
});

test("drift: consistent manifest (version == tool + files present) -> 0.5", () => {
  const repo = fixture();
  writeFileSync(
    join(repo, ".ai-native.yml"),
    `schemaVersion: 1\ntool: spooner\nversion: "${TOOL_VERSION}"\nstages:\n  2:\n    date: "2026-08-06"\n    files:\n      - ".commitlintrc.json"\n`,
  );
  writeFileSync(join(repo, ".commitlintrc.json"), "{}\n");
  assert.equal(item(repo, "drift")?.score, 0.5);
  rmSync(repo, { recursive: true, force: true });
});

test("drift: version current but a declared file missing -> 0.3 with a restore-stage fix", () => {
  const repo = fixture();
  writeFileSync(
    join(repo, ".ai-native.yml"),
    `schemaVersion: 1\ntool: spooner\nversion: "${TOOL_VERSION}"\nstages:\n  4:\n    date: "2026-08-06"\n    files:\n      - "docs/sdd/spec.md"\n`,
  );
  const d = item(repo, "drift");
  assert.equal(d?.score, 0.3);
  assert.match(d?.fix ?? "", /stage 4/);
  rmSync(repo, { recursive: true, force: true });
});

// --- freshness: per-stack dependency locks (review 2026-08-06) -----------------

test("fresh-deps: go.mod + go.sum -> 0.5 (checksum lockfile)", () => {
  const repo = fixture();
  writeFileSync(join(repo, "go.mod"), "module x\n");
  writeFileSync(join(repo, "go.sum"), "checksum\n");
  assert.equal(item(repo, "fresh-deps")?.score, 0.5);
  rmSync(repo, { recursive: true, force: true });
});

test("fresh-deps: go.mod without go.sum -> 0.2", () => {
  const repo = fixture();
  writeFileSync(join(repo, "go.mod"), "module x\n");
  assert.equal(item(repo, "fresh-deps")?.score, 0.2);
  rmSync(repo, { recursive: true, force: true });
});

test("fresh-deps: Cargo.toml + Cargo.lock -> 0.5; without lock -> 0.3", () => {
  const repo = fixture();
  writeFileSync(join(repo, "Cargo.toml"), '[package]\nname = "x"\n');
  writeFileSync(join(repo, "Cargo.lock"), "lock\n");
  assert.equal(item(repo, "fresh-deps")?.score, 0.5);
  rmSync(join(repo, "Cargo.lock"));
  assert.equal(item(repo, "fresh-deps")?.score, 0.3);
  rmSync(repo, { recursive: true, force: true });
});

test("fresh-deps: java manifest pins versions -> 0.3 (no lockfile convention)", () => {
  const repo = fixture();
  writeFileSync(join(repo, "pom.xml"), "<project/>\n");
  assert.equal(item(repo, "fresh-deps")?.score, 0.3);
  rmSync(repo, { recursive: true, force: true });
});

test("agents-commands evidence: requirements.txt-only python — no phantom pyproject.toml (regression 2026-08-07)", () => {
  const repo = fixture();
  writeFileSync(join(repo, "requirements.txt"), "requests==2.31.0\n");
  const r = item(repo, "agents-commands");
  assert.ok(r, "agents-commands missing");
  assert.match(r.evidence, /requirements\.txt/, `evidence: ${r.evidence}`);
  assert.doesNotMatch(r.evidence, /pyproject\.toml/, `evidence names a file that does not exist: ${r.evidence}`);
  rmSync(repo, { recursive: true, force: true });
});

// --- acceptance 6: hook quality ----------------------------------------------

test("cfg-hooks: no config -> 0", () => {
  const repo = fixture();
  assert.equal(item(repo, "cfg-hooks")?.score, 0);
  rmSync(repo, { recursive: true, force: true });
});

test("cfg-hooks: config present but hooks not installed -> 0.2 (regression: dead gate)", () => {
  const repo = fixture();
  writeFileSync(join(repo, ".pre-commit-config.yaml"), "repos:\n  - repo: r\n    hooks: [{id: commitlint}]\n");
  writeFileSync(join(repo, ".commitlintrc.json"), '{"extends": ["@commitlint/config-conventional"]}\n');
  const r = item(repo, "cfg-hooks");
  assert.equal(r?.score, 0.2);
  assert.match(r?.evidence ?? "", /hooks not installed/);
  rmSync(repo, { recursive: true, force: true });
});

test("cfg-hooks: hooks installed incl. commit-msg -> 0.5", () => {
  const repo = fixture();
  writeFileSync(join(repo, ".pre-commit-config.yaml"), "repos:\n  - repo: r\n    hooks: [{id: commitlint}]\n");
  writeFileSync(join(repo, ".commitlintrc.json"), '{"extends": ["@commitlint/config-conventional"]}\n');
  mkdirSync(join(repo, ".git", "hooks"), { recursive: true });
  writeFileSync(join(repo, ".git", "hooks", "pre-commit"), "generated by pre-commit\n");
  writeFileSync(join(repo, ".git", "hooks", "commit-msg"), "generated by pre-commit\n");
  assert.equal(item(repo, "cfg-hooks")?.score, 0.5);
  rmSync(repo, { recursive: true, force: true });
});

// --- acceptance 7: monorepo sub-stack note -----------------------------------

test("subStacks: root node + backend/python -> python named with its dir", () => {
  const repo = fixture();
  writeFileSync(join(repo, "package.json"), "{}\n");
  mkdirSync(join(repo, "backend"), { recursive: true });
  writeFileSync(join(repo, "backend", "pyproject.toml"), "");
  const r = runAudit(repo);
  assert.deepEqual(r.subStacks, [{ stack: "python", dir: "backend" }]);
  // the sub-stack note surfaces in the markdown report (rendering side)
  assert.match(renderMarkdown(r), /Sub-stacks: python \(backend\/\)/);
  rmSync(repo, { recursive: true, force: true });
});

test("subStacks: vendored dirs never count", () => {
  const repo = fixture();
  mkdirSync(join(repo, "node_modules"), { recursive: true });
  writeFileSync(join(repo, "node_modules", "package.json"), "{}\n");
  mkdirSync(join(repo, ".venv"), { recursive: true });
  writeFileSync(join(repo, ".venv", "pyproject.toml"), "");
  assert.deepEqual(runAudit(repo).subStacks, []);
  rmSync(repo, { recursive: true, force: true });
});

test("subStacks: flat repo -> empty", () => {
  const repo = fixture();
  assert.deepEqual(runAudit(repo).subStacks, []);
  rmSync(repo, { recursive: true, force: true });
});

// --- acceptance 8: fix alignment + fix-source audit --------------------------

test("fix alignment: cfg-format fix names no transform when formatter is missing", () => {
  const repo = fixture();
  const r = item(repo, "cfg-format");
  assert.ok(!/transform Stage/.test(r?.fix ?? ""), `fix references transform: ${r?.fix}`);
  assert.match(r?.fix ?? "", /prettier|biome|formatter/);
  rmSync(repo, { recursive: true, force: true });
});

test("fix alignment: cfg-test fix never references a transform stage (never invents commands)", () => {
  const repo = fixture();
  const r = item(repo, "cfg-test");
  assert.ok(!/transform Stage/.test(r?.fix ?? ""), `fix references transform: ${r?.fix}`);
  assert.match(r?.fix ?? "", /never invents commands/);
  rmSync(repo, { recursive: true, force: true });
});

test("fix-source audit: every 'transform Stage N' fix belongs to a deliverable check", () => {
  const repo = fixture();
  const r = runAudit(repo);
  // Checks transform stages 2/3/4 can actually address (M13 matrix).
  const deliverable = new Set([
    "agents-md",
    "agents-bridge",
    "agents-length",
    "agents-sdd",
    "cfg-lint",
    "cfg-hooks",
    "cfg-ci",
    "sec-scan",
    "sec-ci",
    "drift",
  ]);
  for (const i of r.items) {
    if (/transform Stage/.test(i.fix)) {
      assert.ok(deliverable.has(i.id), `${i.id} fix references transform but is not deliverable: ${i.fix}`);
    }
  }
  rmSync(repo, { recursive: true, force: true });
});

// --- acceptance 9: suggestion filtering --------------------------------------

test("suggestions: README with sections silences the README suggestion", () => {
  const repo = fixture();
  writeFileSync(join(repo, "README.md"), "# R\n\n## Install\n\nSteps.\n\n## Usage\n\nMore.\n\n## License\n\nMIT.\n");
  const r = runAudit(repo);
  assert.ok(
    !r.suggestions.some((s) => /README/i.test(s)),
    `README suggestion still present: ${r.suggestions.join(" | ")}`,
  );
  rmSync(repo, { recursive: true, force: true });
});

test("suggestions: missing README keeps the structure suggestion", () => {
  const repo = fixture();
  const r = runAudit(repo);
  assert.ok(r.suggestions.some((s) => /organize sources/i.test(s)));
  rmSync(repo, { recursive: true, force: true });
});

// --- kept regressions ---------------------------------------------------------

test("agents-sdd: hyphenated repo name must not false-positive (regression: sdd-app)", () => {
  const repo = fixture();
  writeFileSync(join(repo, "AGENTS.md"), "# sdd-app\n\nSee README.md for docs.\n");
  assert.equal(item(repo, "agents-sdd")?.score, 0);
  rmSync(repo, { recursive: true, force: true });
});

test("agents-sdd: declaration + spec files with state frontmatter -> 0.4", () => {
  const repo = fixture();
  writeFileSync(
    join(repo, "AGENTS.md"),
    "# repo\n\nWe use a spec-driven workflow (SDD): every feature starts as a spec.\n",
  );
  mkdirSync(join(repo, "specs", "001-x"), { recursive: true });
  writeFileSync(join(repo, "specs", "001-x", "spec.md"), "---\nstatus: proposed\ntarget: M1\n---\n\n# X\n");
  assert.equal(item(repo, "agents-sdd")?.score, 0.4);
  rmSync(repo, { recursive: true, force: true });
});

test("agents-commands: package.json build+test -> 0.6 (no third command)", () => {
  const repo = fixture();
  writeFileSync(join(repo, "package.json"), '{"name":"x","scripts":{"build":"echo b","test":"echo t"}}\n');
  const r = item(repo, "agents-commands");
  assert.equal(r?.score, 0.6);
  rmSync(repo, { recursive: true, force: true });
});

test("agents-commands: package.json build+test+lint -> 0.8 (documented -> 1.0)", () => {
  const repo = fixture();
  writeFileSync(
    join(repo, "package.json"),
    '{"name":"x","scripts":{"build":"echo b","test":"echo t","lint":"echo l"}}\n',
  );
  assert.equal(item(repo, "agents-commands")?.score, 0.8);
  writeFileSync(
    join(repo, "AGENTS.md"),
    "## Commands (all real and executable)\n\n| Command | Purpose |\n|---|---|\n| `npm run build` | build |\n| `npm run test` | test |\n",
  );
  assert.equal(item(repo, "agents-commands")?.score, 1);
  rmSync(repo, { recursive: true, force: true });
});

test("agents-commands: go.mod -> 0.8 via stack lifecycle incl. go vet (M6 + dogfood 2026-08-09)", () => {
  const repo = fixture();
  writeFileSync(join(repo, "go.mod"), "module x\n");
  const r = item(repo, "agents-commands");
  // 0.8, not 0.6: go vet is the stack's canonical lint gate (the generated
  // pre-commit config runs it) — a Makefile-less Go repo no longer stalls at
  // build+test-only (dogfood review: a Makefile-less Go repo scored 0.6 forever)
  assert.equal(r?.score, 0.8);
  assert.match(r?.evidence ?? "", /go\.mod/);
  rmSync(repo, { recursive: true, force: true });
});

// --- review regression: cross-platform security jobs --------------------------

test("sec-ci: GitLab top-level security job counts as dedicated (0-indent)", () => {
  const repo = fixture();
  writeFileSync(
    join(repo, ".gitlab-ci.yml"),
    "lint:\n  script: npm run lint\ntest:\n  script: npm test\nsecurity:\n  script: gitleaks scan\n",
  );
  assert.equal(item(repo, "sec-ci")?.score, 0.5);
  rmSync(repo, { recursive: true, force: true });
});

test("sec-ci: GitHub step named 'security scan' is not a job (deep indent)", () => {
  const repo = ciFixture(
    "jobs:\n  lint:\n    runs-on: ubuntu-latest\n    steps:\n      - name: security scan\n        run: trivy fs .\n",
  );
  assert.equal(item(repo, "sec-ci")?.score, 0.2);
  rmSync(repo, { recursive: true, force: true });
});

// --- 2026-08-07 review regressions -------------------------------------------

test("struct-readme: lowercase readme.md scores identically to README.md (case-insensitive lookup)", () => {
  const lower = fixture();
  writeFileSync(join(lower, "readme.md"), "# r\n\n## A\n\n## B\n\n## C\n\nbody body body body body body body\n");
  const upper = fixture();
  writeFileSync(join(upper, "README.md"), "# r\n\n## A\n\n## B\n\n## C\n\nbody body body body body body body\n");
  const l = item(lower, "struct-readme");
  const u = item(upper, "struct-readme");
  assert.equal(l?.score, u?.score, "lowercase readme must score the same as README");
  assert.match(l?.evidence ?? "", /readme\.md: \d+ chars with 3 section headings/);
  assert.equal(l?.score, 0.5);
  rmSync(lower, { recursive: true, force: true });
  rmSync(upper, { recursive: true, force: true });
});

test("cfg-test: java repo with junit + src/test scores full (regression: no test framework found)", () => {
  const repo = fixture();
  mkdirSync(join(repo, "src/main/java"), { recursive: true });
  mkdirSync(join(repo, "src/test/java"), { recursive: true });
  writeFileSync(
    join(repo, "pom.xml"),
    "<project><modelVersion>4.0.0</modelVersion><groupId>x</groupId><artifactId>x</artifactId><version>1.0</version><dependencies><dependency><groupId>org.junit.jupiter</groupId><artifactId>junit-jupiter</artifactId><version>5.10.0</version><scope>test</scope></dependency></dependencies></project>\n",
  );
  writeFileSync(
    join(repo, "src/test/java/FooTest.java"),
    "package x;\nimport org.junit.jupiter.api.Test;\nclass FooTest {\n  @Test void works() { assert 1 == 1; }\n}\n",
  );
  const r = item(repo, "cfg-test");
  assert.equal(r?.score, 0.5, `evidence: ${r?.evidence}`);
  assert.match(r?.evidence ?? "", /pom\.xml \(mvn compile\/test\)/);
  assert.match(r?.evidence ?? "", /test file\(s\) with assertions/);
  rmSync(repo, { recursive: true, force: true });
});

// --- review regression: ruff.toml symmetry, requirements.txt blind spot, static trace (2026-08-07) ---

test("cfg-format: ruff.toml counts as a formatter config (symmetry with cfg-lint)", () => {
  const repo = fixture();
  writeFileSync(join(repo, "ruff.toml"), '[lint]\nselect = ["E", "F"]\n');
  const f = item(repo, "cfg-format");
  assert.equal(f?.score, 0.2, `cfg-format ${f?.score} ${f?.evidence}`);
  assert.match(f?.evidence ?? "", /ruff\.toml/);
  assert.equal(item(repo, "cfg-lint")?.score, 0.2, "cfg-lint must stay symmetric");
  // no CI files exist — the evidence must not claim a CI step (report truth)
  assert.doesNotMatch(f?.evidence ?? "", /CI format step/, `phantom CI step: ${f?.evidence}`);
  assert.doesNotMatch(item(repo, "cfg-lint")?.evidence ?? "", /CI lint step/);
  rmSync(repo, { recursive: true, force: true });
});

test("fresh-deps: fully-pinned requirements.txt is a manifest pin, not 'no dependency manifest'", () => {
  const repo = fixture();
  writeFileSync(join(repo, "requirements.txt"), "requests==2.31.0\nflask==3.0.0\n");
  const r = item(repo, "fresh-deps");
  assert.equal(r?.score, 0.3, `evidence: ${r?.evidence}`);
  assert.match(r?.evidence ?? "", /pins exact versions/);
  rmSync(repo, { recursive: true, force: true });
});

test("fresh-deps: unpinned requirements.txt scores 0.1; +uv.lock scores 0.5", () => {
  const repo = fixture();
  writeFileSync(join(repo, "requirements.txt"), "requests>=2.0\n");
  assert.equal(item(repo, "fresh-deps")?.score, 0.1);
  writeFileSync(join(repo, "uv.lock"), "version = 1\n");
  assert.equal(item(repo, "fresh-deps")?.score, 0.5);
  rmSync(repo, { recursive: true, force: true });
});

test("agents-commands: evidence marks static trace by default (not executed)", () => {
  const repo = fixture();
  writeFileSync(join(repo, "package.json"), '{"name":"x","scripts":{"build":"echo b","test":"echo t"}}\n');
  const r = item(repo, "agents-commands");
  assert.equal(r?.score, 0.6);
  assert.match(r?.evidence ?? "", /static trace, not executed/);
  rmSync(repo, { recursive: true, force: true });
});

test("agents-commands --verify: passing lifecycle commands are marked verified", () => {
  const repo = fixture();
  writeFileSync(join(repo, "package.json"), '{"name":"x","scripts":{"build":"node -e 1","test":"node -e 1"}}\n');
  const r = runAudit(repo, true).items.find((i) => i.id === "agents-commands");
  assert.match(r?.evidence ?? "", /verified: lifecycle commands passed/);
  rmSync(repo, { recursive: true, force: true });
});

test("agents-commands --verify: failing command is reported, not hidden", () => {
  const repo = fixture();
  writeFileSync(join(repo, "package.json"), '{"name":"x","scripts":{"test":"node -e \\"process.exit(3)\\""}}\n');
  const r = runAudit(repo, true).items.find((i) => i.id === "agents-commands");
  assert.match(r?.evidence ?? "", /FAILED \(exit 3/);
  rmSync(repo, { recursive: true, force: true });
});

test("agents-commands --verify: missing tool is not a failing build (exit 127)", () => {
  const repo = fixture();
  writeFileSync(join(repo, "package.json"), '{"name":"x","scripts":{"test":"spooner-definitely-not-a-tool xyz"}}\n');
  const r = runAudit(repo, true).items.find((i) => i.id === "agents-commands");
  assert.match(r?.evidence ?? "", /is not installed \(exit 127\)/);
  rmSync(repo, { recursive: true, force: true });
});

// --- php signals: composer locking, phpunit tracing, php tool configs (2026-08-07) ---

test("fresh-deps: php-only repo with composer.lock scores 0.5, not 'no dependency manifest'", () => {
  const repo = fixture();
  writeFileSync(join(repo, "composer.json"), '{"require":{"laravel/framework":"^11.0"}}\n');
  assert.equal(item(repo, "fresh-deps")?.score, 0.3, "composer.json without lock");
  writeFileSync(join(repo, "composer.lock"), '{"packages":[]}\n');
  const r = item(repo, "fresh-deps");
  assert.equal(r?.score, 0.5);
  assert.match(r?.evidence ?? "", /composer\.json \+ composer\.lock/);
  rmSync(repo, { recursive: true, force: true });
});

test("fresh-deps: mixed node+php — composer.lock counts, no false 'no lockfile'", () => {
  const repo = fixture();
  writeFileSync(join(repo, "package.json"), '{"name":"x","scripts":{"build":"echo b"}}\n');
  writeFileSync(join(repo, "composer.json"), '{"require":{"laravel/framework":"^11.0"}}\n');
  writeFileSync(join(repo, "composer.lock"), '{"packages":[]}\n');
  const r = item(repo, "fresh-deps");
  assert.equal(r?.score, 0.5, `evidence: ${r?.evidence}`);
  assert.match(r?.evidence ?? "", /composer\.lock/);
  rmSync(repo, { recursive: true, force: true });
});

test("cfg-test: php repo with phpunit.xml + PHPUnit assertions scores full", () => {
  const repo = fixture();
  mkdirSync(join(repo, "tests"), { recursive: true });
  writeFileSync(join(repo, "composer.json"), '{"require-dev":{"phpunit/phpunit":"^11.0"}}\n');
  writeFileSync(join(repo, "phpunit.xml"), '<?xml version="1.0"?><phpunit/>\n');
  writeFileSync(
    join(repo, "tests/FooTest.php"),
    "<?php\nuse PHPUnit\\Framework\\TestCase;\nclass FooTest extends TestCase {\n  public function testWorks(): void { $this->assertTrue(true); }\n}\n",
  );
  const r = item(repo, "cfg-test");
  assert.equal(r?.score, 0.5, `evidence: ${r?.evidence}`);
  assert.match(r?.evidence ?? "", /phpunit/);
  rmSync(repo, { recursive: true, force: true });
});

test("agents-commands: php-only repo traces phpunit — test-only lifecycle reaches 0.6, not 0.4 (dogfood 2026-08-09)", () => {
  const repo = fixture();
  writeFileSync(join(repo, "composer.json"), '{"require-dev":{"phpunit/phpunit":"^11.0"}}\n');
  writeFileSync(join(repo, "phpunit.xml"), '<?xml version="1.0"?><phpunit/>\n');
  const r = item(repo, "agents-commands");
  // php has no build concept — the test command IS the complete lifecycle
  assert.equal(r?.score, 0.6, `evidence: ${r?.evidence}`);
  assert.match(r?.evidence ?? "", /phpunit/);
  rmSync(repo, { recursive: true, force: true });
});

test("agents-commands: mixed node+php — phpunit traced alongside package.json scripts", () => {
  const repo = fixture();
  writeFileSync(join(repo, "package.json"), '{"name":"x","scripts":{"build":"echo b"}}\n');
  writeFileSync(join(repo, "composer.json"), '{"require-dev":{"phpunit/phpunit":"^11.0"}}\n');
  writeFileSync(join(repo, "phpunit.xml"), '<?xml version="1.0"?><phpunit/>\n');
  const r = item(repo, "agents-commands");
  assert.match(r?.evidence ?? "", /package\.json scripts/);
  assert.match(r?.evidence ?? "", /phpunit/);
  rmSync(repo, { recursive: true, force: true });
});

test("cfg-lint/cfg-format: php tool configs score (phpstan.neon / .php-cs-fixer.php)", () => {
  const repo = fixture();
  writeFileSync(join(repo, "phpstan.neon"), "parameters:\n  level: 8\n");
  assert.equal(item(repo, "cfg-lint")?.score, 0.2);
  writeFileSync(join(repo, ".php-cs-fixer.php"), "<?php\nreturn (new PhpCsFixer\\Config());\n");
  assert.equal(item(repo, "cfg-format")?.score, 0.2);
  rmSync(repo, { recursive: true, force: true });
});

// --- hook-ecosystem honesty: yorkie recognition + existence ≠ execution (2026-08-07) ---

test("cfg-hooks: yorkie field mechanism + matching hook content scores full (vue2 chain)", () => {
  const repo = fixture();
  writeFileSync(
    join(repo, "package.json"),
    '{"devDependencies":{"yorkie":"^2.0.0"},"yorkie":{"hooks":{"pre-commit":"lint-staged","commit-msg":"commitlint -E HUSKY_GIT_PARAMS"}}}\n',
  );
  writeFileSync(join(repo, ".commitlintrc.json"), '{"extends":["@commitlint/config-conventional"]}\n');
  writeFileSync(join(repo, ".lintstagedrc"), '{"*.js":["eslint"]}\n');
  mkdirSync(join(repo, ".git", "hooks"), { recursive: true });
  writeFileSync(
    join(repo, ".git", "hooks", "pre-commit"),
    "#!/bin/sh\nnode node_modules/yorkie/bin/runner.js pre-commit\n",
  );
  writeFileSync(
    join(repo, ".git", "hooks", "commit-msg"),
    "#!/bin/sh\nnode node_modules/yorkie/bin/runner.js commit-msg\n",
  );
  const r = item(repo, "cfg-hooks");
  assert.equal(r?.score, 0.5, `evidence: ${r?.evidence}`);
  assert.match(r?.evidence ?? "", /yorkie/);
  rmSync(repo, { recursive: true, force: true });
});

test("cfg-hooks: pre-commit config + yorkie-installed hook files -> not active (existence ≠ execution)", () => {
  const repo = fixture();
  writeFileSync(join(repo, ".pre-commit-config.yaml"), "repos:\n  - repo: r\n    hooks: [{id: commitlint}]\n");
  writeFileSync(join(repo, ".commitlintrc.json"), '{"extends":["@commitlint/config-conventional"]}\n');
  mkdirSync(join(repo, ".git", "hooks"), { recursive: true });
  writeFileSync(
    join(repo, ".git", "hooks", "pre-commit"),
    "#!/bin/sh\nnode node_modules/yorkie/bin/runner.js pre-commit\n",
  );
  writeFileSync(
    join(repo, ".git", "hooks", "commit-msg"),
    "#!/bin/sh\nnode node_modules/yorkie/bin/runner.js commit-msg\n",
  );
  const r = item(repo, "cfg-hooks");
  assert.equal(r?.score, 0.2, `score inflated: ${r?.evidence}`);
  assert.match(r?.evidence ?? "", /hooks not installed/);
  rmSync(repo, { recursive: true, force: true });
});

test("cfg-hooks: .lintstagedrc + .commitlintrc.json -> discipline recognized, hooks not installed -> 0.2", () => {
  const repo = fixture();
  writeFileSync(join(repo, ".lintstagedrc"), '{"*.js":["eslint"]}\n');
  writeFileSync(join(repo, ".commitlintrc.json"), '{"extends":["@commitlint/config-conventional"]}\n');
  const r = item(repo, "cfg-hooks");
  // 0.2 (not 0.1) proves the discipline config is recognized — the old code
  // read only the mechanism file content and reported "no commitlint discipline"
  assert.equal(r?.score, 0.2, `evidence: ${r?.evidence}`);
  assert.match(r?.evidence ?? "", /hooks not installed/);
  rmSync(repo, { recursive: true, force: true });
});

// --- kotlin/Android: gradle kts, ktlint, module layout (2026-08-07) ---

test("kotlin Android repo: build.gradle.kts scores fresh-deps + struct-layout module dirs", () => {
  const repo = fixture();
  writeFileSync(join(repo, "settings.gradle.kts"), 'rootProject.name = "app"\ninclude(":app")\n');
  mkdirSync(join(repo, "app", "src", "main", "java"), { recursive: true });
  writeFileSync(join(repo, "app", "build.gradle.kts"), 'plugins { id("com.android.application") }\n');
  assert.equal(item(repo, "fresh-deps")?.score, 0.3, "build.gradle.kts is a manifest pin");
  const layout = item(repo, "struct-layout");
  assert.equal(layout?.score, 0.5, `evidence: ${layout?.evidence}`);
  assert.match(layout?.evidence ?? "", /gradle module dirs/);
  rmSync(repo, { recursive: true, force: true });
});

test("cfg-format/cfg-lint: ktlint via .editorconfig ktlint_ keys or ktlint.toml", () => {
  const repo = fixture();
  writeFileSync(join(repo, ".editorconfig"), "root = true\n[*.kt]\nktlint_standard = enabled\n");
  assert.equal(item(repo, "cfg-format")?.score, 0.2, "editorconfig ktlint keys count");
  assert.match(item(repo, "cfg-format")?.evidence ?? "", /ktlint/);
  assert.equal(item(repo, "cfg-lint")?.score, 0.2, "ktlint is also a linter");
  writeFileSync(join(repo, "ktlint.toml"), 'disabled_rules = ["no-wildcard-imports"]\n');
  assert.match(item(repo, "cfg-format")?.evidence ?? "", /ktlint\.toml/);
  rmSync(repo, { recursive: true, force: true });
});

test("cfg-test: kotlin tests in app/src/test/java score (module dirs + .kt extension)", () => {
  const repo = fixture();
  mkdirSync(join(repo, "app", "src", "test", "java"), { recursive: true });
  writeFileSync(join(repo, "app", "build.gradle.kts"), 'plugins { id("com.android.application") }\n');
  writeFileSync(
    join(repo, "app", "src", "test", "java", "MainTest.kt"),
    "package x\nimport org.junit.Test\nclass MainTest {\n  @Test fun works() { assert(true) }\n}\n",
  );
  const r = item(repo, "cfg-test");
  assert.ok((r?.score ?? 0) >= 0.4, `evidence: ${r?.evidence}`);
  assert.match(r?.evidence ?? "", /test file/);
  rmSync(repo, { recursive: true, force: true });
});

// --- dogfood review 2026-08-09: go-stack fairness --------------------

test("struct-layout: go cmd/ + pkg/ layout scores (dogfood: go)", () => {
  const repo = fixture();
  writeFileSync(join(repo, "go.mod"), "module example.com/godemo\n\ngo 1.24\n");
  mkdirSync(join(repo, "cmd"), { recursive: true });
  mkdirSync(join(repo, "pkg"), { recursive: true });
  const r = item(repo, "struct-layout");
  assert.equal(r?.score, 0.5);
  assert.match(r?.evidence ?? "", /cmd\/ \+ pkg\/ \(Go layout\)/);
  rmSync(repo, { recursive: true, force: true });
});

test("struct-layout: go repo without cmd/pkg stays 0 (no false credit)", () => {
  const repo = fixture();
  writeFileSync(join(repo, "go.mod"), "module example.com/x\n\ngo 1.24\n");
  assert.equal(item(repo, "struct-layout")?.score, 0);
  rmSync(repo, { recursive: true, force: true });
});

test("cfg-format: generated gofmt gate counts as config + command (dogfood: go)", () => {
  const repo = fixture();
  writeFileSync(join(repo, "go.mod"), "module example.com/godemo\n\ngo 1.24\n");
  writeFileSync(
    join(repo, ".pre-commit-config.yaml"),
    "repos:\n  - repo: local\n    hooks:\n      - id: gofmt\n        name: gofmt (format check)\n        entry: gofmt -l .\n        language: system\n",
  );
  const r = item(repo, "cfg-format");
  assert.equal(r?.score, 0.4, `evidence: ${r?.evidence}`);
  assert.match(r?.evidence ?? "", /gofmt/);
  rmSync(repo, { recursive: true, force: true });
});

test("cfg-format: no gofmt gate -> no credit (unchanged behavior)", () => {
  const repo = fixture();
  writeFileSync(join(repo, "go.mod"), "module example.com/x\n\ngo 1.24\n");
  assert.equal(item(repo, "cfg-format")?.score, 0);
  rmSync(repo, { recursive: true, force: true });
});

test("cfg-lint: go stack traces go vet as the lint command (dogfood: go)", () => {
  const repo = fixture();
  writeFileSync(join(repo, "go.mod"), "module example.com/godemo\n\ngo 1.24\n");
  writeFileSync(join(repo, ".golangci.yaml"), "run:\n  timeout: 5m\n");
  mkdirSync(join(repo, ".github", "workflows"), { recursive: true });
  writeFileSync(
    join(repo, ".github", "workflows", "ci.yml"),
    "jobs:\n  lint:\n    runs-on: ubuntu-latest\n    steps:\n      - run: golangci-lint run\n",
  );
  const r = item(repo, "cfg-lint");
  assert.equal(r?.score, 0.5, `evidence: ${r?.evidence}`);
  assert.match(r?.evidence ?? "", /go vet \.\/\.\.\./);
  rmSync(repo, { recursive: true, force: true });
});

test("agents-md: generated go contract lists 3 traceable commands (dogfood: go)", () => {
  const repo = fixture();
  writeFileSync(join(repo, "go.mod"), "module example.com/godemo\n\ngo 1.24\n");
  const contract = [
    "# godemo — agent contract",
    "> Generated by spooner transform Stage 3.",
    "## Commands (all real and executable)",
    "| Command | Purpose |",
    "|---|---|",
    "| `go build ./...` | build |",
    "| `go test ./...` | test |",
    "| `go vet ./...` | vet |",
  ].join("\n");
  writeFileSync(join(repo, "AGENTS.md"), contract);
  const r = item(repo, "agents-md");
  assert.equal(r?.score, 0.5, `evidence: ${r?.evidence}`);
  assert.match(r?.evidence ?? "", /3 traceable commands/);
  rmSync(repo, { recursive: true, force: true });
});

test("agents-commands: go stack with documented contract reaches 1.0 (dogfood: go)", () => {
  const repo = fixture();
  writeFileSync(join(repo, "go.mod"), "module example.com/godemo\n\ngo 1.24\n");
  const contract = [
    "# godemo — agent contract",
    "## Commands (all real and executable)",
    "| Command | Purpose |",
    "|---|---|",
    "| `go build ./...` | build |",
    "| `go test ./...` | test |",
    "| `go vet ./...` | vet |",
  ].join("\n");
  writeFileSync(join(repo, "AGENTS.md"), contract);
  const r = item(repo, "agents-commands");
  assert.equal(r?.score, 1, `evidence: ${r?.evidence}`);
  rmSync(repo, { recursive: true, force: true });
});

test("makefile: assignments and special targets are not phantom targets (dogfood: go-monorepo)", () => {
  const repo = fixture();
  writeFileSync(
    join(repo, "Makefile"),
    [
      "PROJECT_NAME := demo",
      "PKG_LIST := $(shell go list ./...)",
      ".PHONY: build",
      "build:",
      "\t@echo building",
      "test: deps",
      "\t@go test ./...",
      "deps:",
      "\t@echo deps ok",
    ].join("\n"),
  );
  writeFileSync(join(repo, "go.mod"), "module x\n");
  const contract = [
    "# x — agent contract",
    "## Commands (all real and executable)",
    "| Command | Purpose |",
    "|---|---|",
    "| `make build` | Makefile target |",
    "| `make test` | Makefile target |",
    "| `make deps` | Makefile target |",
  ].join("\n");
  writeFileSync(join(repo, "AGENTS.md"), contract);
  const md = item(repo, "agents-md");
  assert.match(md?.evidence ?? "", /3 traceable commands/);
  assert.doesNotMatch(md?.evidence ?? "", /PROJECT_NAME|\.PHONY/, "phantom targets traceable");
  rmSync(repo, { recursive: true, force: true });
});

// --- dogfood review 2026-08-09: python stack fairness --------

test("cfg-lint/cfg-format: generated ruff gate counts as config + command (dogfood: python)", () => {
  const repo = fixture();
  writeFileSync(join(repo, "requirements.txt"), "requests==2.31.0\n");
  writeFileSync(
    join(repo, ".pre-commit-config.yaml"),
    "# pre-commit config generated by spooner transform Stage 2\nrepos:\n  - repo: https://github.com/astral-sh/ruff-pre-commit\n    rev: v0.16.1\n    hooks:\n      - id: ruff\n        files: \\.py$\n      - id: ruff-format\n        args: [--check]\n        files: \\.py$\n",
  );
  mkdirSync(join(repo, ".github", "workflows"), { recursive: true });
  writeFileSync(
    join(repo, ".github", "workflows", "ci.yml"),
    "jobs:\n  lint-test:\n    steps:\n      - run: ruff check\n      - run: ruff format --check\n",
  );
  const lint = item(repo, "cfg-lint");
  const fmt = item(repo, "cfg-format");
  assert.equal(lint?.score, 0.5, `cfg-lint evidence: ${lint?.evidence}`);
  assert.equal(fmt?.score, 0.5, `cfg-format evidence: ${fmt?.evidence}`);
  assert.match(lint?.evidence ?? "", /ruff \(generated pre-commit gate\)/);
  assert.match(fmt?.evidence ?? "", /ruff-format \(generated pre-commit gate\)/);
  rmSync(repo, { recursive: true, force: true });
});

test("agents-commands: python test-only lifecycle + ruff gate + documentation reaches 1.0 (dogfood: python)", () => {
  const repo = fixture();
  writeFileSync(join(repo, "requirements.txt"), "requests==2.31.0\n");
  writeFileSync(
    join(repo, ".pre-commit-config.yaml"),
    "repos:\n  - repo: https://github.com/astral-sh/ruff-pre-commit\n    hooks:\n      - id: ruff\n",
  );
  const contract = [
    "# x — agent contract",
    "## Commands (all real and executable)",
    "| Command | Purpose |",
    "|---|---|",
    "| `python3 -m unittest` | test |",
  ].join("\n");
  writeFileSync(join(repo, "AGENTS.md"), contract);
  const r = item(repo, "agents-commands");
  assert.equal(r?.score, 1, `evidence: ${r?.evidence}`);
  rmSync(repo, { recursive: true, force: true });
});

test("struct-layout: python flat top-level packages score (dogfood: python)", () => {
  const repo = fixture();
  writeFileSync(join(repo, "requirements.txt"), "requests==2.31.0\n");
  mkdirSync(join(repo, "model"), { recursive: true });
  mkdirSync(join(repo, "ui"), { recursive: true });
  writeFileSync(join(repo, "model", "dae.py"), "import torch\n");
  writeFileSync(join(repo, "ui", "panel.py"), "import sys\n");
  const r = item(repo, "struct-layout");
  assert.equal(r?.score, 0.5, `evidence: ${r?.evidence}`);
  assert.match(r?.evidence ?? "", /flat top-level packages \(Python layout\)/);
  rmSync(repo, { recursive: true, force: true });
});

// --- dogfood review 2026-08-10: security job names ----------------

test("sec-ci/cfg-ci: a pip-audit job is a dedicated security job (dogfood: monorepo)", () => {
  const repo = ciFixture(
    "jobs:\n  pip-audit:\n    runs-on: ubuntu-latest\n    steps: [{ run: pip-audit -r requirements.txt }]\n",
  );
  const sec = item(repo, "sec-ci");
  const ci = item(repo, "cfg-ci");
  assert.equal(sec?.score, 0.5, `sec-ci evidence: ${sec?.evidence}`);
  // security-only CI scores 0.1 on depth, but the security signal is counted
  assert.equal(ci?.score, 0.1, `cfg-ci evidence: ${ci?.evidence}`);
  assert.match(ci?.evidence ?? "", /security: true/);
  rmSync(repo, { recursive: true, force: true });
});

test("sec-ci: a codeql workflow is a dedicated security job despite its job name", () => {
  const repo = ciFixture(
    "jobs:\n  analyze:\n    runs-on: ubuntu-latest\n    steps:\n      - uses: github/codeql-action/init@v3\n",
  );
  const sec = item(repo, "sec-ci");
  assert.equal(sec?.score, 0.5, `sec-ci evidence: ${sec?.evidence}`);
  rmSync(repo, { recursive: true, force: true });
});

// --- dogfood review 2026-08-10: co-located tests + WXT layout ----

test("cfg-test: co-located *.test.ts files count (vitest convention — dogfood: wxt)", () => {
  const repo = fixture();
  writeFileSync(join(repo, "package.json"), '{"name":"x","scripts":{"test":"vitest"}}\n');
  mkdirSync(join(repo, "utils"), { recursive: true });
  writeFileSync(
    join(repo, "utils", "local-cache.test.ts"),
    "import { describe, it, expect } from 'vitest';\ndescribe('cache', () => { it('works', () => expect(1).toBe(1)); });\n",
  );
  const r = item(repo, "cfg-test");
  assert.ok((r?.score ?? 0) >= 0.4, `evidence: ${r?.evidence}`);
  assert.match(r?.evidence ?? "", /test file\(s\)/);
  rmSync(repo, { recursive: true, force: true });
});

test("struct-layout: WXT entrypoints/ layout scores (dogfood: wxt)", () => {
  const repo = fixture();
  writeFileSync(join(repo, "package.json"), '{"name":"x"}\n');
  mkdirSync(join(repo, "entrypoints", "popup"), { recursive: true });
  writeFileSync(join(repo, "entrypoints", "popup", "index.html"), "<html></html>\n");
  const r = item(repo, "struct-layout");
  assert.equal(r?.score, 0.5, `evidence: ${r?.evidence}`);
  assert.match(r?.evidence ?? "", /entrypoints\/ \(WXT layout\)/);
  rmSync(repo, { recursive: true, force: true });
});

test("detect: rush.json marks a Rush monorepo as node (dogfood: rush)", () => {
  const repo = fixture();
  writeFileSync(
    join(repo, "rush.json"),
    '{ "$schema": "https://developer.microsoft.com/json-schemas/rush/v5/rush.schema.json" }\n',
  );
  mkdirSync(join(repo, "apps", "agent"), { recursive: true });
  writeFileSync(join(repo, "apps", "agent", "package.json"), '{"name":"agent"}\n');
  const r = runAudit(repo);
  assert.deepEqual(r.stacks, ["node"]);
  rmSync(repo, { recursive: true, force: true });
});

test("cfg-lint/cfg-format: a repo-owned ruff config is credited but not labeled generated (dogfood: repo-owned)", () => {
  const repo = fixture();
  writeFileSync(join(repo, "requirements.txt"), "requests==2.31.0\n");
  writeFileSync(
    join(repo, ".pre-commit-config.yaml"),
    "repos:\n  - repo: https://github.com/astral-sh/ruff-pre-commit\n    rev: v0.1.6\n    hooks:\n      - id: ruff\n      - id: ruff-format\n",
  );
  const lint = item(repo, "cfg-lint");
  const fmt = item(repo, "cfg-format");
  assert.ok((lint?.score ?? 0) >= 0.2, `cfg-lint evidence: ${lint?.evidence}`);
  assert.match(lint?.evidence ?? "", /ruff \(pre-commit hook\)/);
  assert.match(fmt?.evidence ?? "", /ruff-format \(pre-commit hook\)/);
  assert.doesNotMatch(lint?.evidence ?? "", /generated/);
  rmSync(repo, { recursive: true, force: true });
});

test("detect: oh-package.json5 marks a HarmonyOS app as harmonyos (dogfood: harmonyos)", () => {
  const repo = fixture();
  writeFileSync(join(repo, "oh-package.json5"), '{ "modelVersion": "26.0.0", "name": "harmonyapp" }\n');
  mkdirSync(join(repo, "entry"), { recursive: true });
  writeFileSync(join(repo, "entry", "oh-package.json5"), '{ "name": "entry" }\n');
  const r = runAudit(repo);
  assert.deepEqual(r.stacks, ["harmonyos"]);
  rmSync(repo, { recursive: true, force: true });
});
