import { test } from "node:test";
import assert from "node:assert/strict";
import { mkdirSync, mkdtempSync, rmSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { tmpdir } from "node:os";
import { runAudit } from "../scripts/audit.ts";

/** Fresh fixture repo (not a git repo — freshness/maturity checks just under-score). */
function fixture(): string {
  return mkdtempSync(join(tmpdir(), "spooner-audit-"));
}

function item(repo: string, id: string) {
  return runAudit(repo).items.find((i) => i.id === id);
}

test("cfg-hooks: no config -> 0", () => {
  const repo = fixture();
  const r = item(repo, "cfg-hooks");
  assert.equal(r?.score, 0);
  rmSync(repo, { recursive: true, force: true });
});

test("cfg-hooks: config present but hooks not installed -> 0.5 (regression: dead gate)", () => {
  const repo = fixture();
  writeFileSync(join(repo, ".pre-commit-config.yaml"), "repos:\n  - repo: r\n    hooks: [{id: commitlint}]\n");
  writeFileSync(join(repo, ".commitlintrc.json"), '{"extends": ["@commitlint/config-conventional"]}\n');
  const r = item(repo, "cfg-hooks");
  assert.equal(r?.score, 0.5);
  assert.match(r?.evidence ?? "", /hooks not installed/);
  rmSync(repo, { recursive: true, force: true });
});

test("cfg-hooks: config + installed git hook -> 1", () => {
  const repo = fixture();
  writeFileSync(join(repo, ".pre-commit-config.yaml"), "repos:\n  - repo: r\n    hooks: [{id: commitlint}]\n");
  writeFileSync(join(repo, ".commitlintrc.json"), '{"extends": ["@commitlint/config-conventional"]}\n');
  mkdirSync(join(repo, ".git", "hooks"), { recursive: true });
  writeFileSync(join(repo, ".git", "hooks", "pre-commit"), "generated by pre-commit\n");
  const r = item(repo, "cfg-hooks");
  assert.equal(r?.score, 1);
  rmSync(repo, { recursive: true, force: true });
});

test("cfg-ci: no CI files -> 0 (regression: hasCi false positive)", () => {
  const repo = fixture();
  const r = item(repo, "cfg-ci");
  assert.equal(r?.score, 0);
  assert.match(r?.evidence ?? "", /no CI config found/);
  rmSync(repo, { recursive: true, force: true });
});

test("cfg-ci: gitlab CI counts as CI (cross-platform honesty)", () => {
  const repo = fixture();
  writeFileSync(join(repo, ".gitlab-ci.yml"), "stages: [build]\n");
  const r = item(repo, "cfg-ci");
  assert.equal(r?.score, 0); // lint+test missing, but content present — score stays 0, evidence shows CI present
  assert.match(r?.evidence ?? "", /CI present/);
  rmSync(repo, { recursive: true, force: true });
});

test("agents-sdd: hyphenated repo name must not false-positive (regression: sdd-app)", () => {
  const repo = fixture();
  writeFileSync(join(repo, "AGENTS.md"), "# sdd-app\n\nSee README.md for docs.\n");
  assert.equal(item(repo, "agents-sdd")?.score, 0);
  rmSync(repo, { recursive: true, force: true });
});

test("agents-sdd: real spec-driven declaration -> 1", () => {
  const repo = fixture();
  writeFileSync(join(repo, "AGENTS.md"), "# repo\n\nWe use a spec-driven workflow (SDD): every feature starts as a spec.\n");
  assert.equal(item(repo, "agents-sdd")?.score, 1);
  rmSync(repo, { recursive: true, force: true });
});

test("agents-commands: package.json build+test scripts -> 2/2", () => {
  const repo = fixture();
  writeFileSync(join(repo, "package.json"), '{"name":"x","scripts":{"build":"echo b","test":"echo t"}}\n');
  const r = item(repo, "agents-commands");
  assert.equal(r?.score, 2);
  rmSync(repo, { recursive: true, force: true });
});

test("agents-commands: go.mod -> 2/2 via stack lifecycle (M6)", () => {
  const repo = fixture();
  writeFileSync(join(repo, "go.mod"), "module x\n");
  const r = item(repo, "agents-commands");
  assert.equal(r?.score, 2);
  assert.match(r?.evidence ?? "", /go\.mod/);
  rmSync(repo, { recursive: true, force: true });
});
