import { test } from "node:test";
import assert from "node:assert/strict";
import { mkdirSync, mkdtempSync, rmSync, symlinkSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { tmpdir } from "node:os";
import { runAudit, renderMarkdown } from "../scripts/audit.ts";
import { TOOL_VERSION } from "../scripts/transform.ts";

/** Fresh fixture repo (not a git repo — freshness/maturity checks just under-score). */
function fixture(): string {
  return mkdtempSync(join(tmpdir(), "spooner-audit-"));
}

function item(repo: string, id: string) {
  return runAudit(repo).items.find((i) => i.id === id);
}

// --- acceptance 1: scale ----------------------------------------------------

test("scale: max 10, category maxima 3/2.5/2/1.5/1, every score is a 0.1 multiple", () => {
  const repo = fixture();
  const r = runAudit(repo);
  assert.equal(r.schemaVersion, 2);
  assert.equal(r.score.max, 10);
  assert.equal(r.score.byCategory["agent-setup"].max, 3);
  assert.equal(r.score.byCategory.configuration.max, 2.5);
  assert.equal(r.score.byCategory.integrity.max, 2);
  assert.equal(r.score.byCategory.freshness.max, 1.5);
  assert.equal(r.score.byCategory.structure.max, 1);
  for (const i of r.items) {
    assert.ok(i.score <= i.max, `${i.id}: score ${i.score} > max ${i.max}`);
    const scaled = i.score * 10;
    assert.ok(Math.abs(scaled - Math.round(scaled)) < 1e-9, `${i.id}: ${i.score} is not a 0.1 multiple`);
  }
  assert.equal(r.score.total, r.items.reduce((s, i) => s + i.score, 0));
  rmSync(repo, { recursive: true, force: true });
});

// --- acceptance 2: quality grading (generated-contract fixture) --------------

test("agents: generated-contract fixture scores top bands", () => {
  const repo = fixture();
  writeFileSync(join(repo, "package.json"), '{"name":"x","scripts":{"build":"echo b","test":"echo t","lint":"echo l"}}\n');
  // 42-line contract with two traceable commands
  const contract = [
    "# x — agent contract",
    "> Generated by spooner transform Stage 3.",
    "## Overview",
    "Demo.",
    "## Commands (all real and executable)",
    "| Command | Purpose |",
    "|---|---|",
    "| `npm run build` | build |",
    "| `npm run test` | test |",
    "",
  ].concat(Array.from({ length: 32 }, (_, i) => `line ${i}`));
  writeFileSync(join(repo, "AGENTS.md"), contract.join("\n"));
  // symlink bridge
  mkdirSync(join(repo, ".git"), { recursive: true });
  writeFileSync(join(repo, ".git", "HEAD"), "ref: refs/heads/main\n");
  try {
    symlinkSync("AGENTS.md", join(repo, "CLAUDE.md"));
  } catch {
    /* symlink may fail on some platforms — bridge test is best-effort */
  }
  const r = runAudit(repo);
  assert.equal(item(repo, "agents-md")?.score, 0.5);
  assert.equal(item(repo, "agents-length")?.score, 0.5);
  const bridge = item(repo, "agents-bridge");
  if (bridge) assert.ok([0.5, 0.3].includes(bridge.score), `bridge ${bridge.score}`);
  rmSync(repo, { recursive: true, force: true });
});

// --- acceptance 3: length banding -------------------------------------------

test("agents-length: 42-line contract -> 0.5 (optimal band)", () => {
  const repo = fixture();
  writeFileSync(join(repo, "AGENTS.md"), Array.from({ length: 42 }, (_, i) => `line ${i}`).join("\n"));
  assert.equal(item(repo, "agents-length")?.score, 0.5);
  rmSync(repo, { recursive: true, force: true });
});

test("agents-length: 220-line contract drops to 0.3", () => {
  const repo = fixture();
  writeFileSync(join(repo, "AGENTS.md"), Array.from({ length: 220 }, (_, i) => `line ${i}`).join("\n"));
  assert.equal(item(repo, "agents-length")?.score, 0.3);
  rmSync(repo, { recursive: true, force: true });
});

// --- acceptance 4: CI depth --------------------------------------------------

function ciFixture(workflow: string): string {
  const repo = fixture();
  mkdirSync(join(repo, ".github", "workflows"), { recursive: true });
  writeFileSync(join(repo, ".github", "workflows", "ci.yml"), workflow);
  return repo;
}

test("cfg-ci: lint-only workflow -> 0.2", () => {
  const repo = ciFixture("jobs:\n  lint:\n    runs-on: ubuntu-latest\n    steps: [{ run: npm run lint }]\n");
  assert.equal(item(repo, "cfg-ci")?.score, 0.2);
  rmSync(repo, { recursive: true, force: true });
});

test("cfg-ci: lint+test -> 0.4", () => {
  const repo = ciFixture("jobs:\n  lint:\n    runs-on: ubuntu-latest\n  test:\n    runs-on: ubuntu-latest\n");
  assert.equal(item(repo, "cfg-ci")?.score, 0.4);
  rmSync(repo, { recursive: true, force: true });
});

test("cfg-ci: lint+test+security job -> 0.5", () => {
  const repo = ciFixture("jobs:\n  lint:\n    runs-on: ubuntu-latest\n  test:\n    runs-on: ubuntu-latest\n  security:\n    runs-on: ubuntu-latest\n");
  assert.equal(item(repo, "cfg-ci")?.score, 0.5);
  rmSync(repo, { recursive: true, force: true });
});

test("cfg-ci: no CI files -> 0 (regression: hasCi false positive)", () => {
  const repo = fixture();
  const r = item(repo, "cfg-ci");
  assert.equal(r?.score, 0);
  assert.match(r?.evidence ?? "", /no CI config found/);
  rmSync(repo, { recursive: true, force: true });
});

test("cfg-ci: gitlab CI with lint+test counts (cross-platform honesty)", () => {
  const repo = fixture();
  writeFileSync(join(repo, ".gitlab-ci.yml"), "stages: [lint, test]\n");
  assert.equal(item(repo, "cfg-ci")?.score, 0.4);
  rmSync(repo, { recursive: true, force: true });
});

// --- acceptance 5: drift quality ---------------------------------------------

test("drift: no manifest -> 0", () => {
  const repo = fixture();
  assert.equal(item(repo, "drift")?.score, 0);
  rmSync(repo, { recursive: true, force: true });
});

test("drift: stale manifest (version != tool) -> 0.2, never full", () => {
  const repo = fixture();
  writeFileSync(join(repo, ".ai-native.yml"), `schemaVersion: 1\ntool: spooner\nversion: "0.0.1"\nstages: {}\n`);
  assert.equal(item(repo, "drift")?.score, 0.2);
  rmSync(repo, { recursive: true, force: true });
});

test("drift: consistent manifest (version == tool + files present) -> 0.5", () => {
  const repo = fixture();
  writeFileSync(join(repo, ".ai-native.yml"), `schemaVersion: 1\ntool: spooner\nversion: "${TOOL_VERSION}"\nstages:\n  2:\n    date: "2026-08-06"\n    files:\n      - ".commitlintrc.json"\n`);
  writeFileSync(join(repo, ".commitlintrc.json"), "{}\n");
  assert.equal(item(repo, "drift")?.score, 0.5);
  rmSync(repo, { recursive: true, force: true });
});

test("drift: version current but a declared file missing -> 0.3 with a restore-stage fix", () => {
  const repo = fixture();
  writeFileSync(join(repo, ".ai-native.yml"), `schemaVersion: 1\ntool: spooner\nversion: "${TOOL_VERSION}"\nstages:\n  4:\n    date: "2026-08-06"\n    files:\n      - "docs/sdd/spec.md"\n`);
  const d = item(repo, "drift");
  assert.equal(d?.score, 0.3);
  assert.match(d?.fix ?? "", /stage 4/);
  rmSync(repo, { recursive: true, force: true });
});

// --- freshness: per-stack dependency locks (review 2026-08-06) -----------------

test("fresh-deps: go.mod + go.sum -> 0.5 (checksum lockfile)", () => {
  const repo = fixture();
  writeFileSync(join(repo, "go.mod"), "module x\n");
  writeFileSync(join(repo, "go.sum"), "checksum\n");
  assert.equal(item(repo, "fresh-deps")?.score, 0.5);
  rmSync(repo, { recursive: true, force: true });
});

test("fresh-deps: go.mod without go.sum -> 0.2", () => {
  const repo = fixture();
  writeFileSync(join(repo, "go.mod"), "module x\n");
  assert.equal(item(repo, "fresh-deps")?.score, 0.2);
  rmSync(repo, { recursive: true, force: true });
});

test("fresh-deps: Cargo.toml + Cargo.lock -> 0.5; without lock -> 0.3", () => {
  const repo = fixture();
  writeFileSync(join(repo, "Cargo.toml"), '[package]\nname = "x"\n');
  writeFileSync(join(repo, "Cargo.lock"), "lock\n");
  assert.equal(item(repo, "fresh-deps")?.score, 0.5);
  rmSync(join(repo, "Cargo.lock"));
  assert.equal(item(repo, "fresh-deps")?.score, 0.3);
  rmSync(repo, { recursive: true, force: true });
});

test("fresh-deps: java manifest pins versions -> 0.3 (no lockfile convention)", () => {
  const repo = fixture();
  writeFileSync(join(repo, "pom.xml"), "<project/>\n");
  assert.equal(item(repo, "fresh-deps")?.score, 0.3);
  rmSync(repo, { recursive: true, force: true });
});

// --- acceptance 6: hook quality ----------------------------------------------

test("cfg-hooks: no config -> 0", () => {
  const repo = fixture();
  assert.equal(item(repo, "cfg-hooks")?.score, 0);
  rmSync(repo, { recursive: true, force: true });
});

test("cfg-hooks: config present but hooks not installed -> 0.2 (regression: dead gate)", () => {
  const repo = fixture();
  writeFileSync(join(repo, ".pre-commit-config.yaml"), "repos:\n  - repo: r\n    hooks: [{id: commitlint}]\n");
  writeFileSync(join(repo, ".commitlintrc.json"), '{"extends": ["@commitlint/config-conventional"]}\n');
  const r = item(repo, "cfg-hooks");
  assert.equal(r?.score, 0.2);
  assert.match(r?.evidence ?? "", /hooks not installed/);
  rmSync(repo, { recursive: true, force: true });
});

test("cfg-hooks: hooks installed incl. commit-msg -> 0.5", () => {
  const repo = fixture();
  writeFileSync(join(repo, ".pre-commit-config.yaml"), "repos:\n  - repo: r\n    hooks: [{id: commitlint}]\n");
  writeFileSync(join(repo, ".commitlintrc.json"), '{"extends": ["@commitlint/config-conventional"]}\n');
  mkdirSync(join(repo, ".git", "hooks"), { recursive: true });
  writeFileSync(join(repo, ".git", "hooks", "pre-commit"), "generated by pre-commit\n");
  writeFileSync(join(repo, ".git", "hooks", "commit-msg"), "generated by pre-commit\n");
  assert.equal(item(repo, "cfg-hooks")?.score, 0.5);
  rmSync(repo, { recursive: true, force: true });
});

// --- acceptance 7: monorepo sub-stack note -----------------------------------

test("subStacks: root node + backend/python -> python named with its dir", () => {
  const repo = fixture();
  writeFileSync(join(repo, "package.json"), "{}\n");
  mkdirSync(join(repo, "backend"), { recursive: true });
  writeFileSync(join(repo, "backend", "pyproject.toml"), "");
  const r = runAudit(repo);
  assert.deepEqual(r.subStacks, [{ stack: "python", dir: "backend" }]);
  // the sub-stack note surfaces in the markdown report (rendering side)
  assert.match(renderMarkdown(r), /Sub-stacks: python \(backend\/\)/);
  rmSync(repo, { recursive: true, force: true });
});

test("subStacks: vendored dirs never count", () => {
  const repo = fixture();
  mkdirSync(join(repo, "node_modules"), { recursive: true });
  writeFileSync(join(repo, "node_modules", "package.json"), "{}\n");
  mkdirSync(join(repo, ".venv"), { recursive: true });
  writeFileSync(join(repo, ".venv", "pyproject.toml"), "");
  assert.deepEqual(runAudit(repo).subStacks, []);
  rmSync(repo, { recursive: true, force: true });
});

test("subStacks: flat repo -> empty", () => {
  const repo = fixture();
  assert.deepEqual(runAudit(repo).subStacks, []);
  rmSync(repo, { recursive: true, force: true });
});

// --- acceptance 8: fix alignment + fix-source audit --------------------------

test("fix alignment: cfg-format fix names no transform when formatter is missing", () => {
  const repo = fixture();
  const r = item(repo, "cfg-format");
  assert.ok(!/transform Stage/.test(r?.fix ?? ""), `fix references transform: ${r?.fix}`);
  assert.match(r?.fix ?? "", /prettier|biome|formatter/);
  rmSync(repo, { recursive: true, force: true });
});

test("fix alignment: cfg-test fix never references a transform stage (never invents commands)", () => {
  const repo = fixture();
  const r = item(repo, "cfg-test");
  assert.ok(!/transform Stage/.test(r?.fix ?? ""), `fix references transform: ${r?.fix}`);
  assert.match(r?.fix ?? "", /never invents commands/);
  rmSync(repo, { recursive: true, force: true });
});

test("fix-source audit: every 'transform Stage N' fix belongs to a deliverable check", () => {
  const repo = fixture();
  const r = runAudit(repo);
  // Checks transform stages 2/3/4 can actually address (M13 matrix).
  const deliverable = new Set(["agents-md", "agents-bridge", "agents-length", "agents-sdd", "cfg-lint", "cfg-hooks", "cfg-ci", "sec-scan", "sec-ci", "drift"]);
  for (const i of r.items) {
    if (/transform Stage/.test(i.fix)) {
      assert.ok(deliverable.has(i.id), `${i.id} fix references transform but is not deliverable: ${i.fix}`);
    }
  }
  rmSync(repo, { recursive: true, force: true });
});

// --- acceptance 9: suggestion filtering --------------------------------------

test("suggestions: README with sections silences the README suggestion", () => {
  const repo = fixture();
  writeFileSync(join(repo, "README.md"), "# R\n\n## Install\n\nSteps.\n\n## Usage\n\nMore.\n\n## License\n\nMIT.\n");
  const r = runAudit(repo);
  assert.ok(!r.suggestions.some((s) => /README/i.test(s)), `README suggestion still present: ${r.suggestions.join(" | ")}`);
  rmSync(repo, { recursive: true, force: true });
});

test("suggestions: missing README keeps the structure suggestion", () => {
  const repo = fixture();
  const r = runAudit(repo);
  assert.ok(r.suggestions.some((s) => /organize sources/i.test(s)));
  rmSync(repo, { recursive: true, force: true });
});

// --- kept regressions ---------------------------------------------------------

test("agents-sdd: hyphenated repo name must not false-positive (regression: sdd-app)", () => {
  const repo = fixture();
  writeFileSync(join(repo, "AGENTS.md"), "# sdd-app\n\nSee README.md for docs.\n");
  assert.equal(item(repo, "agents-sdd")?.score, 0);
  rmSync(repo, { recursive: true, force: true });
});

test("agents-sdd: declaration + spec files with state frontmatter -> 0.4", () => {
  const repo = fixture();
  writeFileSync(join(repo, "AGENTS.md"), "# repo\n\nWe use a spec-driven workflow (SDD): every feature starts as a spec.\n");
  mkdirSync(join(repo, "specs", "001-x"), { recursive: true });
  writeFileSync(join(repo, "specs", "001-x", "spec.md"), "---\nstatus: proposed\ntarget: M1\n---\n\n# X\n");
  assert.equal(item(repo, "agents-sdd")?.score, 0.4);
  rmSync(repo, { recursive: true, force: true });
});

test("agents-commands: package.json build+test -> 0.6 (no third command)", () => {
  const repo = fixture();
  writeFileSync(join(repo, "package.json"), '{"name":"x","scripts":{"build":"echo b","test":"echo t"}}\n');
  const r = item(repo, "agents-commands");
  assert.equal(r?.score, 0.6);
  rmSync(repo, { recursive: true, force: true });
});

test("agents-commands: package.json build+test+lint -> 0.8 (documented -> 1.0)", () => {
  const repo = fixture();
  writeFileSync(join(repo, "package.json"), '{"name":"x","scripts":{"build":"echo b","test":"echo t","lint":"echo l"}}\n');
  assert.equal(item(repo, "agents-commands")?.score, 0.8);
  writeFileSync(join(repo, "AGENTS.md"), "## Commands (all real and executable)\n\n| Command | Purpose |\n|---|---|\n| `npm run build` | build |\n| `npm run test` | test |\n");
  assert.equal(item(repo, "agents-commands")?.score, 1);
  rmSync(repo, { recursive: true, force: true });
});

test("agents-commands: go.mod -> 0.6 via stack lifecycle (M6)", () => {
  const repo = fixture();
  writeFileSync(join(repo, "go.mod"), "module x\n");
  const r = item(repo, "agents-commands");
  assert.equal(r?.score, 0.6);
  assert.match(r?.evidence ?? "", /go\.mod/);
  rmSync(repo, { recursive: true, force: true });
});

// --- review regression: cross-platform security jobs --------------------------

test("sec-ci: GitLab top-level security job counts as dedicated (0-indent)", () => {
  const repo = fixture();
  writeFileSync(join(repo, ".gitlab-ci.yml"), "lint:\n  script: npm run lint\ntest:\n  script: npm test\nsecurity:\n  script: gitleaks scan\n");
  assert.equal(item(repo, "sec-ci")?.score, 0.5);
  rmSync(repo, { recursive: true, force: true });
});

test("sec-ci: GitHub step named 'security scan' is not a job (deep indent)", () => {
  const repo = ciFixture("jobs:\n  lint:\n    runs-on: ubuntu-latest\n    steps:\n      - name: security scan\n        run: trivy fs .\n");
  assert.equal(item(repo, "sec-ci")?.score, 0.2);
  rmSync(repo, { recursive: true, force: true });
});
